### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by justinrhodes** [jfrux/dd-wrt-bootstrap-theme#1]
This looks great and is exactly what I'm looking for. How can I get this working with my DDWRT setup?

**Comment by jfrux** [comment]
I wish it were that easy... :-/
I'm still developing it and since dd-wrt requires the "design" to be BUILT into the compiled dd-wrt firmware it's tricky to get that to happen without managing your own builds.

Mine is running using a firefox / chrome plugin called "dot.js" and it's loading a single css / js file hosted elsewhere on page load.

And once it's cached you don't really see any difference... it's kind of a client side override so to speak.

**Comment by jfrux** [comment]
Also, the workaround sucks because it's not going to benefit mobile users which is precisely the point of the bootstrap usage to begin with.
Here are screenshots of the basics... think they might be a bit outdated though.
![screen shot 2014-01-25 at 11 35 45 pm](https://f.cloud.github.com/assets/171077/2066809/a2523ffc-8cf3-11e3-9cef-2d68fdd866ba.png)
![screen shot 2014-01-25 at 11 36 36 pm](https://f.cloud.github.com/assets/171077/2066810/a257c346-8cf3-11e3-96ea-4c476c555936.png)
![screen shot 2014-01-25 at 11 37 31 pm](https://f.cloud.github.com/assets/171077/2066811/a2585f68-8cf3-11e3-9585-42e87e80083d.png)

**Comment by jfrux** [comment]
Oh and... I'm not sure dd-wrt's process is to get a new official theme added as an option or default but I'd love to give enough pressure to them to try to persuade to have this added as a simple theme option to choose from.

I'd say they would need enough thumbs up from end-users to get it put in play.

**Comment by jfrux** [comment]
More up to date screenshot:
![screen shot 2014-02-05 at 1 43 30 pm](https://f.cloud.github.com/assets/171077/2090514/9b4c17ca-8e95-11e3-9f7e-cf9a95666430.png)

**Comment by Rowdster** [comment]
How do we get this effort more visibility?  I'm ready to mobile admin my devices at this time.  

Awesome effort, especially with all the challenges.  Congrats on getting this far!

**Comment by antoniobenedetti** [comment]
The screenshot looks great. Please ask the dd-wrt devs to include this theme in their beta builds, it looks awesome. They should make it the default theme. :)

**Comment by antoniobenedetti** [comment]
Nevermind, i opened a ticket myself: http://svn.dd-wrt.com/ticket/3311
Also, is the github repo updated with the latest source from the up-to-date screenshot?

**Comment by jfrux** [comment]
This isn't really in the right format to be embedded into the firmware... but we could get it there if I could restructure the markup a bit within the builds.  But dunno how easy that is or if it's even possible.. :-/

**Comment by antoniobenedetti** [comment]
It just looks so awesome from the latest screenshot.. i wish it could be integrated in the firmware. The current themes are outdated and they look like from 2005 :/

**Comment by antoniobenedetti** [comment]
Anyways, i hope you can convert it in the right firmware format in your free time. Or maybe the main devs could convert it. I really really love this theme.

**Comment by drawz** [comment]
You might have more success getting this accepted into OpenWrt. I know I'd love to see it there. Even if not officially accepted, it would be easy to distribute the theme yourself. There's already a bootstrap theme in fact, which you could use as a starting point if desired.

**Comment by antoniobenedetti** [comment]
OpenWRT already has a bootstrap theme as you said. So there is no need to port it. DD-WRT has really bad looking themes but it has great features, so i think it is way more important to get it working on DD-WRT firmware.

**Comment by jfrux** [comment]
Sorry, misread your comments as saying there was already an existing dd-wrt bootstrap theme. haha.

Never the less, when I get free time I'm going to get working on a build of dd-wrt with bootstrap3 support.  I can't justify my time right now, but will in the near future hopefully!
